
DIRS = laux geom calib ba features random ransac sequence singlecam relax pcloud

install:
	for d in $(DIRS); do\
	  cd $$d; make install; cd ..;\
	done

clean:
	for d in $(DIRS); do\
	  cd $$d; make clean; cd ..;\
	done








