DIRS = singlecam singlecam_nlin calib track relax pclcalib defpcl debug 

install:
	for d in $(DIRS); do\
	  cd $$d; make install; cd ..;\
	done

clean:
	for d in $(DIRS); do\
	  cd $$d; make clean; cd ..;\
	done









